#ifndef SCANNER_HPP
#define SCANNER_HPP

#if !defined(yyFlexLexerOnce)
#include <FlexLexer.h>
#endif

#include "parser.hpp" // File generated by Bison, contains yyParser::symbol_type

namespace yy {
    class Scanner : public yyFlexLexer {
    public:
        // Constructor that accepts the input stream (file or cin)
        Scanner(std::istream *in) : yyFlexLexer(in) {}

        // Hiding the original yylex() method that returns int
        // and defining a new one that returns symbol_type
        // This is the method that Bison will call to get tokens
        using FlexLexer::yylex;
        virtual yy::yyParser::symbol_type lex();
    };
}

#endif // SCANNER_HPP